version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gradle-patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      gradle-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "npm"
    directory: "/src/main/frontend"
    schedule:
      interval: "weekly"
    groups:
      npm-patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      docker-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
