spring:
  datasource:
    url: jdbc:postgresql://db:5432/chpay

  security:
    oauth2:
      client:
        provider:
          wisvchconnect:
            issuer-uri: http://oidc:8080
            authorization-uri: http://localhost:3083/connect/authorize
