services:
  app:
    build:
      dockerfile: Dockerfile.dev
    container_name: chpay-app
    working_dir: /workspace
    command: sleep infinity
    init: true
    volumes:
      - .:/workspace:cached
      - gradle-cache:/home/dev/.gradle
      - m2-cache:/home/dev/.m2
    environment:
      SPRING_PROFILES_ACTIVE: devcontainer
    depends_on:
      - db
      - mailcatcher
      - oidc
      - frontend-watch
    ports:
      - "3080:3080"

volumes:
  gradle-cache:
  m2-cache:
  frontend-node-modules:
